# config/config.yaml

profile_defaults: &defaults
  logging:
    level: INFO
    json: true

  database:
    # Prefer DSN from env; these serve as fallbacks
    dsn: ${POSTGRES_DSN}
    pool_size: 10
    pool_timeout_s: 30

  duckdb:
    path: ${DUCKDB_PATH}

  storage:
    kind: ${STORAGE_TYPE:-s3}            # s3|local
    s3:
      endpoint_url: ${S3_ENDPOINT_URL}
      region: ${S3_REGION}
      bucket: ${S3_BUCKET}
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
      use_ssl: ${S3_USE_SSL}
    fs:  # Standardized key for local filesystem storage
      root: ${LOCAL_STORAGE_ROOT:-./data/raw}
      max_size_gb: ${LOCAL_STORAGE_MAX_GB:-10}
      fallback_s3: ${LOCAL_STORAGE_FALLBACK_S3:-true}

  ingestion:
    ctgov:
      base_url: https://clinicaltrials.gov/api/v2
      backfill_start: "2000-01-01"
      batch_size: 500
      sleep_ms: 200
      capture_version_history: true
    sec:
      rate_limit_per_min: 6
      user_agent: ${SEC_USER_AGENT}
    pubs:
      unpaywall_email: ${UNPAYWALL_EMAIL}
      openalex_email: ${OPENALEX_EMAIL}
    patents:
      uspto_endpoint: https://developer.uspto.gov/ds-api
      inpadoc_family: true

  entity_mapping:
    exchanges_whitelist: ["NYSE","NASDAQ","NYSE American","OTCQX","OTCQB"]
    name_match_threshold: 0.98
    alias_boost: 0.02
    domain_match_required: true
    asset_backstop_enabled: true

  extraction:
    use_langextract: true
    max_pages: 50
    keep_spans: true

  linking_heuristics:
    # Feature flags for auto-promotion
    auto_promote_enabled: false  # Disabled until precision validation
    min_labeled_precision: 0.95  # Minimum 95% precision required
    min_labeled_links: 50        # Minimum 50 labeled links required
    
    # Confidence thresholds (uncalibrated - use with caution)
    confidence_thresholds:
      auto_promote: 0.95        # Only used when auto_promote_enabled = true
      high_confidence: 0.85     # For review prioritization
      review_required: 0.70     # Below this needs human review
    
    # Heuristic-specific settings
    heuristics:
      hp1_nct_near_asset:
        enabled: true
        confidence: 1.00        # Highest confidence
        description: "NCT ID within ±250 chars of asset mention"
      
      hp2_exact_intervention_match:
        enabled: false           # Disabled - not implemented
        confidence: 0.95        # Placeholder - not used
        description: "Asset alias matches trial intervention name (requires CT.gov cache)"
      
      hp3_company_pr_bias:
        enabled: true
        confidence: 0.90        # Uncalibrated - needs validation
        description: "Company-hosted PR with code + INN, no ambiguity"
      
      hp4_abstract_specificity:
        enabled: true
        confidence: 0.85        # Uncalibrated - needs validation
        description: "Abstract title has asset + body has phase/indication"
    
    # Conflict resolution
    conflict_resolution:
      downgrade_amount: 0.20    # Downgrade confidence for conflicts
      combo_patterns:           # Patterns that indicate combo therapy
        - "combination"
        - "in combination with"
        - "plus"
        - "arm a"
        - "arm b"

  signals:
    p_value_cusp_range: [0.045, 0.050]
    power_min_threshold: 0.70
    effect_size_graveyard_percentile: 0.75
    dropout_imbalance_threshold: 0.20
    multiplicity_control_required: true

  gates:
    # Gates are co-dependent; define which primitives are required
    G1_alpha_meltdown: {requires: ["S1","S2"]}
    G2_analysis_gaming: {requires: ["S3","S4"]}
    G3_plausibility: {requires_any: ["S6","S7"], also_requires: ["S5"]}
    G4_p_hacking: {requires: ["S8"], requires_any: ["S1","S3"]}

  scoring:
    prior_failure_rate: 0.55               # π0 baseline for universe
    likelihood_ratios:
      G1: 5.0
      G2: 6.0
      G3: 4.0
      G4: 3.5
      # primitives default near 1.0 unless calibrated
    stop_rules:
      endpoint_switched_after_LPR: 0.97    # set P_fail
      pp_only_success_with_itt_missing_gt: 0.97
      unblinded_subjective_primary_when_blinding_feasible: 0.97
    freeze_window_days: 14

  evaluation:
    precision_at_k: [1, 3]
    pfail_thresholds: [0.8, 0.9, 0.95]

local:
  <<: *defaults

staging:
  <<: *defaults
  logging:
    level: INFO

prod:
  <<: *defaults
  logging:
    level: WARNING
